export const MAIN_ROUTE = '/'
export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const CATALOG_ROUTE = '/catalog'
export const PRODUCT_ROUTE = '/product'
export const BASKET_ROUTE = '/basket'
