export const FETCH_PRODUCTS = 'PRODUCT/FETCH_PRODUCTS'
export const CREATE_PRODUCT = 'PRODUCT/CREATE_PRODUCT'
export const EDIT_PRODUCT = 'PRODUCT/EDIT_PRODUCT'

export const DELETE_PRODUCT = 'PRODUCT/DELETE_PRODUCT'
export const REQUEST_PRODUCTS = 'PRODUCT/REQUEST_PRODUCTS'

// export const SET_NEW_PRODUCT = 'SET_NEW_PRODUCT';
// export const SET_EDIT_PRODUCT = 'SET_EDIT_PRODUCT';
// export const SET_IS_ACTIVE_ROW = 'SET_IS_ACTIVE_ROW';
export const EDIT_PRODUCT_SUCCESS = 'PRODUCT/EDIT_PRODUCT_SUCCESS'
export const EDIT_PRODUCT_FAILURE = 'PRODUCT/EDIT_PRODUCT_FAILURE'